// Generates AI assistant rule adapters from .claude/skills/*/SKILL.md.
//
// Source of truth: .claude/skills/<name>/SKILL.md (Ring format YAML + body).
// Targets:
//   - .cursor/rules/<name>.mdc          (Cursor)
//   - .windsurf/rules/<name>.md         (Windsurf)
//   - .clinerules/<name>.md             (Cline)
//   - .continue/rules/<name>.md         (Continue.dev)
//   - CONVENTIONS.md                    (Aider, consolidated)
//
// Run: node scripts/sync-rules.mjs
// Cross-platform (Node 24+, no shell, no extra deps).

import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = resolve(fileURLToPath(import.meta.url), '..', '..');
const SKILLS_DIR = join(REPO_ROOT, '.claude', 'skills');

const GENERATED_HEADER_LINES = [
  '<!--',
  '  AUTO-GENERATED by scripts/sync-rules.mjs from .claude/skills/<name>/SKILL.md.',
  '  DO NOT EDIT THIS FILE DIRECTLY. Edit the source skill and run: npm run sync:rules',
  '-->',
];

// Per-skill adapter metadata.
// alwaysApply -> Cursor `alwaysApply: true` and Windsurf `trigger: always_on`.
// globs -> Cursor `globs` (file patterns where this rule kicks in) and Windsurf `globs`.
// description -> short one-liner Cursor uses to decide relevance.
const ADAPTER_CONFIG = {
  adr: {
    alwaysApply: true,
    globs: [],
    description: 'Architectural decisions need an ADR before implementation.',
  },
  'readable-code': {
    alwaysApply: true,
    globs: [],
    description: 'Every line of code must be explicitly readable. No magic numbers, no nested ternaries.',
  },
  'doc-sync': {
    alwaysApply: true,
    globs: [],
    description: 'After every code change, evaluate if README, CLAUDE.md, docs or ADRs need updating.',
  },
  'tdd-workflow': {
    alwaysApply: false,
    globs: ['src/**/*.ts'],
    description: 'TDD Red-Green-Refactor. Tests are always written before production code.',
  },
  'safe-refactoring': {
    alwaysApply: false,
    globs: ['src/**/*.ts'],
    description: 'Refactoring through parallel implementation with feature toggles. Never modify existing code directly.',
  },
  'ddd-patterns': {
    alwaysApply: false,
    globs: ['src/modules/**/domain/**', 'src/shared/domain/**'],
    description: 'Tactical and strategic DDD patterns: entities, value objects, aggregates, domain events.',
  },
  'hexagonal-architecture': {
    alwaysApply: false,
    globs: ['src/**/*.ts'],
    description: 'Ports & Adapters. Dependencies point inward. Domain has zero framework imports.',
  },
  'pr-template': {
    alwaysApply: false,
    globs: [],
    description: 'Every Pull Request follows the project PR template.',
  },
  'code-review': {
    alwaysApply: false,
    globs: [],
    description: 'Code review with Mermaid diagram showing execution cycle and findings positioned in flow.',
  },
  'task-breakdown': {
    alwaysApply: false,
    globs: [],
    description: 'Decompose ADRs into low/medium complexity PRs with correct dependency order.',
  },
  'project-onboarding': {
    alwaysApply: false,
    globs: [],
    description: 'Welcome new devs to the DDD Template, point to the right docs.',
  },
  'architecture-explainer': {
    alwaysApply: false,
    globs: [],
    description: 'Deep dives into the template architectural patterns when asked "how does X work".',
  },
  'module-walkthrough': {
    alwaysApply: false,
    globs: [],
    description: 'Step-by-step walkthroughs for adding bounded contexts, aggregates, use cases, domain events.',
  },
};

const DEFAULT_CONFIG = {
  alwaysApply: false,
  globs: [],
  description: '',
};

function listSkillDirectories() {
  let entries = [];
  try {
    entries = readdirSync(SKILLS_DIR);
  } catch (error) {
    process.stderr.write(`[sync-rules] Cannot read ${SKILLS_DIR}: ${error.message}\n`);
    process.exit(1);
  }

  const skillNames = [];
  for (const entry of entries) {
    const fullPath = join(SKILLS_DIR, entry);
    if (statSync(fullPath).isDirectory()) {
      const skillFile = join(fullPath, 'SKILL.md');
      try {
        statSync(skillFile);
        skillNames.push(entry);
      } catch {
        // skip directories without SKILL.md
      }
    }
  }
  return skillNames.sort();
}

function readSkill(skillName) {
  const filePath = join(SKILLS_DIR, skillName, 'SKILL.md');
  const raw = readFileSync(filePath, 'utf8');
  const frontmatter = extractFrontmatter(raw);
  const body = extractBody(raw);
  return {
    name: skillName,
    frontmatter,
    body,
    config: ADAPTER_CONFIG[skillName] ?? DEFAULT_CONFIG,
  };
}

function extractFrontmatter(raw) {
  const trimmed = raw.replace(/^﻿/, '');
  if (!trimmed.startsWith('---')) {
    return { name: '', description: '', trigger: '', skip_when: '' };
  }
  const closingIndex = trimmed.indexOf('\n---', 3);
  if (closingIndex === -1) {
    return { name: '', description: '', trigger: '', skip_when: '' };
  }
  const header = trimmed.slice(3, closingIndex);
  return parseSimpleYaml(header);
}

function extractBody(raw) {
  const trimmed = raw.replace(/^﻿/, '');
  if (!trimmed.startsWith('---')) return trimmed;
  const closingIndex = trimmed.indexOf('\n---', 3);
  if (closingIndex === -1) return trimmed;
  const afterClose = trimmed.slice(closingIndex + 4);
  return afterClose.replace(/^\r?\n/, '');
}

function parseSimpleYaml(text) {
  const result = { name: '', description: '', trigger: '', skip_when: '' };
  const lines = text.split(/\r?\n/);

  let lineIndex = 0;
  while (lineIndex < lines.length) {
    const line = lines[lineIndex];
    const inlineMatch = line.match(/^([a-zA-Z_][a-zA-Z0-9_]*):\s*(.*)$/);
    if (!inlineMatch) {
      lineIndex += 1;
      continue;
    }
    const key = inlineMatch[1];
    const valuePart = inlineMatch[2];

    if (valuePart === '|' || valuePart === '|-' || valuePart === '|+') {
      const collected = [];
      lineIndex += 1;
      while (lineIndex < lines.length) {
        const nextLine = lines[lineIndex];
        if (nextLine.length === 0) {
          collected.push('');
          lineIndex += 1;
          continue;
        }
        const indentMatch = nextLine.match(/^(\s+)(.*)$/);
        if (!indentMatch) break;
        collected.push(indentMatch[2]);
        lineIndex += 1;
      }
      result[key] = collected.join('\n').trim();
      continue;
    }

    if (valuePart.length > 0) {
      result[key] = valuePart.trim();
    }
    lineIndex += 1;
  }
  return result;
}

function shortDescription(skill) {
  if (skill.config.description) return skill.config.description;
  const fmDescription = skill.frontmatter.description || '';
  const firstLine = fmDescription.split('\n')[0]?.trim() || '';
  if (firstLine.length > 0) return firstLine;
  return `Skill: ${skill.name}`;
}

function clearGeneratedDir(absolutePath) {
  try {
    rmSync(absolutePath, { recursive: true, force: true });
  } catch {
    // ignore
  }
  mkdirSync(absolutePath, { recursive: true });
}

function ensureDir(absolutePath) {
  mkdirSync(absolutePath, { recursive: true });
}

function generateCursorAdapter(skills) {
  const targetDir = join(REPO_ROOT, '.cursor', 'rules');
  clearGeneratedDir(targetDir);

  for (const skill of skills) {
    const description = shortDescription(skill);
    const frontmatter = ['---'];

    if (skill.config.alwaysApply) {
      // Cursor "Always Apply": only alwaysApply + optional description.
      frontmatter.push(`description: ${escapeYamlScalar(description)}`);
      frontmatter.push('alwaysApply: true');
    } else if (skill.config.globs.length > 0) {
      // Cursor "Auto Attached": globs as comma-separated string (NOT array).
      frontmatter.push(`description: ${escapeYamlScalar(description)}`);
      frontmatter.push(`globs: ${skill.config.globs.join(', ')}`);
      frontmatter.push('alwaysApply: false');
    } else {
      // Cursor "Agent Requested": description only, agent decides.
      frontmatter.push(`description: ${escapeYamlScalar(description)}`);
      frontmatter.push('alwaysApply: false');
    }

    frontmatter.push('---');

    const lines = [
      ...frontmatter,
      '',
      ...GENERATED_HEADER_LINES,
      '',
      `# ${skill.name}`,
      '',
      `> Source of truth: \`.claude/skills/${skill.name}/SKILL.md\``,
      '',
      buildRuleBody(skill),
    ];

    writeFileSync(join(targetDir, `${skill.name}.mdc`), lines.join('\n') + '\n', 'utf8');
  }

  writeIndex(targetDir, 'README.md', skills, '.mdc');
}

function generateWindsurfAdapter(skills) {
  const targetDir = join(REPO_ROOT, '.windsurf', 'rules');
  clearGeneratedDir(targetDir);

  for (const skill of skills) {
    const description = shortDescription(skill);
    const frontmatter = ['---'];

    if (skill.config.alwaysApply) {
      // Windsurf "always_on": full rule in every prompt; no globs needed.
      frontmatter.push('trigger: always_on');
      frontmatter.push(`description: ${escapeYamlScalar(description)}`);
    } else if (skill.config.globs.length > 0) {
      // Windsurf "glob": activates when Cascade reads/edits matching files.
      frontmatter.push('trigger: glob');
      frontmatter.push(`description: ${escapeYamlScalar(description)}`);
      frontmatter.push(`globs: ${skill.config.globs.join(', ')}`);
    } else {
      // Windsurf "model_decision": only description shown; model decides relevance.
      frontmatter.push('trigger: model_decision');
      frontmatter.push(`description: ${escapeYamlScalar(description)}`);
    }

    frontmatter.push('---');

    const lines = [
      ...frontmatter,
      '',
      ...GENERATED_HEADER_LINES,
      '',
      `# ${skill.name}`,
      '',
      `> Source of truth: \`.claude/skills/${skill.name}/SKILL.md\``,
      '',
      buildRuleBody(skill),
    ];

    writeFileSync(join(targetDir, `${skill.name}.md`), lines.join('\n') + '\n', 'utf8');
  }

  writeIndex(targetDir, 'README.md', skills, '.md');
}

function generateClineAdapter(skills) {
  const targetDir = join(REPO_ROOT, '.clinerules');
  clearGeneratedDir(targetDir);

  for (const skill of skills) {
    const description = shortDescription(skill);
    const lines = [
      ...GENERATED_HEADER_LINES,
      '',
      `# ${skill.name}`,
      '',
      `> ${description}`,
      `> Source of truth: \`.claude/skills/${skill.name}/SKILL.md\``,
      '',
      buildRuleBody(skill),
    ];
    writeFileSync(join(targetDir, `${skill.name}.md`), lines.join('\n') + '\n', 'utf8');
  }

  writeIndex(targetDir, 'README.md', skills, '.md');
}

function generateContinueAdapter(skills) {
  const targetDir = join(REPO_ROOT, '.continue', 'rules');
  clearGeneratedDir(targetDir);

  for (const skill of skills) {
    const description = shortDescription(skill);
    const lines = [
      ...GENERATED_HEADER_LINES,
      '',
      `# ${skill.name}`,
      '',
      `> ${description}`,
      `> Source of truth: \`.claude/skills/${skill.name}/SKILL.md\``,
      '',
      buildRuleBody(skill),
    ];
    writeFileSync(join(targetDir, `${skill.name}.md`), lines.join('\n') + '\n', 'utf8');
  }

  writeIndex(targetDir, 'README.md', skills, '.md');
}

function generateAiderConventions(skills) {
  const targetPath = join(REPO_ROOT, 'CONVENTIONS.md');

  const tableRows = skills.map((skill) => `- **${skill.name}** — ${shortDescription(skill)}`);

  const sections = skills.map((skill) => {
    const triggerLine = skill.frontmatter.trigger
      ? `\n**When it applies:**\n\n${skill.frontmatter.trigger}\n`
      : '';
    const skipLine = skill.frontmatter.skip_when
      ? `\n**When to skip:**\n\n${skill.frontmatter.skip_when}\n`
      : '';
    return [
      `## ${skill.name}`,
      '',
      `> ${shortDescription(skill)}`,
      '',
      triggerLine,
      skipLine,
      buildRuleBody(skill),
    ]
      .filter((part) => part.length > 0)
      .join('\n');
  });

  const lines = [
    ...GENERATED_HEADER_LINES,
    '',
    '# Conventions (Aider / generic agents)',
    '',
    '> AUTO-GENERATED. Edit `.claude/skills/<name>/SKILL.md` and run `npm run sync:rules`.',
    '',
    'Authoritative source: [`.claude/skills/`](.claude/skills/).',
    'For a higher-level overview, see [`AGENTS.md`](AGENTS.md) and [`CLAUDE.md`](CLAUDE.md).',
    '',
    '## Skill Index',
    '',
    ...tableRows,
    '',
    '---',
    '',
    sections.join('\n\n---\n\n'),
  ];

  writeFileSync(targetPath, lines.join('\n') + '\n', 'utf8');
}

function buildRuleBody(skill) {
  const triggerSection = skill.frontmatter.trigger
    ? `**Trigger:**\n\n${skill.frontmatter.trigger}\n\n`
    : '';
  const skipSection = skill.frontmatter.skip_when
    ? `**Skip when:**\n\n${skill.frontmatter.skip_when}\n\n`
    : '';
  return `${triggerSection}${skipSection}${skill.body.trim()}`;
}

function writeIndex(targetDir, fileName, skills, extension) {
  const lines = [
    ...GENERATED_HEADER_LINES,
    '',
    '# Generated rules',
    '',
    '> AUTO-GENERATED. Edit `.claude/skills/<name>/SKILL.md` and run `npm run sync:rules`.',
    '',
  ];
  for (const skill of skills) {
    lines.push(`- [${skill.name}](${skill.name}${extension}) — ${shortDescription(skill)}`);
  }
  writeFileSync(join(targetDir, fileName), lines.join('\n') + '\n', 'utf8');
}

function escapeYamlScalar(value) {
  if (value.includes(':') || value.includes('#') || value.includes('"')) {
    const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}"`;
  }
  return value;
}

function main() {
  const skillNames = listSkillDirectories();
  if (skillNames.length === 0) {
    process.stderr.write('[sync-rules] No skills found in .claude/skills/. Aborting.\n');
    process.exit(1);
  }

  const skills = skillNames.map(readSkill);

  generateCursorAdapter(skills);
  generateWindsurfAdapter(skills);
  generateClineAdapter(skills);
  generateContinueAdapter(skills);
  generateAiderConventions(skills);

  process.stdout.write(
    `[sync-rules] Generated adapters for ${skills.length} skills:\n` +
      `  - .cursor/rules/       (${skills.length} files)\n` +
      `  - .windsurf/rules/     (${skills.length} files)\n` +
      `  - .clinerules/         (${skills.length} files)\n` +
      `  - .continue/rules/     (${skills.length} files)\n` +
      `  - CONVENTIONS.md       (consolidated)\n`,
  );
}

main();
